# Generated by Django 4.2.6 on 2023-12-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjek', models.CharField(max_length=255)),
                ('pesan', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
