# Generated by Django 4.2.10 on 2024-03-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KontakModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('pesan', models.TextField()),
            ],
        ),
    ]
