# Generated by Django 4.2.10 on 2024-04-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_artikel_penulis'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='tag',
            field=models.CharField(default='django python', max_length=25),
            preserve_default=False,
        ),
    ]
