# Generated by Django 4.2.6 on 2023-11-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.publication'),
        ),
    ]
