# Generated by Django 4.2.10 on 2024-05-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulangpergi', '0002_alter_tujuan_nm_penumpang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tujuan',
            name='nm_penumpang',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
