# Generated by Django 4.2.13 on 2024-05-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulangpergi', '0003_alter_tujuan_nm_penumpang'),
    ]

    operations = [
        migrations.AddField(
            model_name='tujuan',
            name='profile',
            field=models.ImageField(blank=True, default='profil.png', upload_to=''),
        ),
    ]
