# Generated by Django 4.2.13 on 2024-05-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulangpergi', '0004_tujuan_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tujuan',
            name='profile',
            field=models.ImageField(blank=True, default='profil.png', upload_to='profiles/'),
        ),
    ]
