# Generated by Django 4.2.10 on 2024-04-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tujuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_penumpang', models.CharField(max_length=50)),
                ('nm_pengemudi', models.CharField(max_length=50)),
                ('tujuan', models.TextField()),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
