# Generated by Django 4.2.10 on 2024-04-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='penulis',
            field=models.CharField(default='admin', max_length=25),
            preserve_default=False,
        ),
    ]
